### ISSUE TITLE
Could you please share the dataset ?

### ISSUE THREAD

**Issue by Raju06** [weningerleon/TextileDefectDetection#1]
This is a great approach in solving the problem. And I would like to learn your approach by testing. Could you please share the dataset, it will be of a great help

**Comment by weningerleon** [comment]
Hi Raju,

Thanks for you interest in this work. However, I'm sorry that I cannot share the dataset.

**Comment by Raju06** [comment]
Thank you for your reply. I do understand the hardwork in collecting data. For studying the code please see if you can upload 4-5 pics for learning by debugging.

**Comment by weningerleon** [comment]
I have to admit that the repository was not very user friendly. It was updated a little bit, with a readme, exemplary images and a pre-trained network. Hope that helps!

**Comment by balarajuyogesh** [comment]
Thank you very much for the update. It is extremely helpful. I will read and understand.
