### ISSUE TITLE
Running with another dataset

### ISSUE THREAD

**Issue by raniaakh** [weningerleon/TextileDefectDetection#3]
Hi.

Thank you for sharing this amazing work!

I want to ask, is it possible to run this code using another dataset? I have my own dataset which produced from textile company. If it is possible, would you like to guide me those steps?

Thank you once again.

**Comment by weningerleon** [comment]
Hi raniaakh,

I'm glad your interested in this work!
It should be possible to run the code on another dataset. However, you will need to manually annotate the floating-points for training, similar to the image you can see in example/fcn_result (see example/orig_fabric for the input data).

If you have any specific questions feel free to ask.
