### ISSUE TITLE
Input data and how to annotate it?

### ISSUE THREAD

**Issue by saqibshakeel035** [weningerleon/TextileDefectDetection#6]
Thanks for sharing the great work. However, I would like to know that how did you annotated your images and in what format you input your data for training (.json file or mask or a text file?).

**Comment by weningerleon** [comment]
Hi,

Thanks for your interest!
We created the annotations using photoshop. For training, we load the
textil images as input, and the mask images as output.

Cheers,
Leon

**Comment by saqibshakeel035** [comment]
Thanks for your quick response. The paper you are referring to that says that  semantic image segmentation is performed for the weft and wrap floating points extraction. If I am not wrong, the input data for the final network is pre-processed by a CNN network for the generation of "bl01.png" in your case and then this image is used in final training ?

**Comment by weningerleon** [comment]
the input data, containing front-light as well as back-light ("bl01.png")
is used as input to the CNN, which creates the black-and-white weft and
warp floating point extraction.

Best,
Leon

**Comment by saqibshakeel035** [comment]
One last question before I close this issue, you said that you annotated your dataset using Photoshop, How many images you annotated and how does an annotated image look like? Any example present in your repo or ?
Many Thanks,

**Comment by weningerleon** [comment]
You can take the exemplary output as an example: https://github.com/weningerleon/TextileDefectDetection/blob/master/example/fcn_result/res01.png
For annotation, you basically do the same (on an image not containing any defects). It's ok if the annotation are not perfect, but just rectangles on top of the warp/weft floating points.
The number of annotations we use depends on the specific textile, you should find the details in the paper

**Comment by saqibshakeel035** [comment]
> You can take the exemplary output as an example: https://github.com/weningerleon/TextileDefectDetection/blob/master/example/fcn_result/res01.png
> For annotation, you basically do the same (on an image not containing any defects). It's ok if the annotation are not perfect, but just rectangles on top of the warp/weft floating points.
> The number of annotations we use depends on the specific textile, you should find the details in the paper

Thanks for your reply, I am still not sure how you generated your  input mask, is it done by using thresholding or photoshop or both?

**Comment by ibtehajali67** [comment]
> > You can take the exemplary output as an example: https://github.com/weningerleon/TextileDefectDetection/blob/master/example/fcn_result/res01.png
> > For annotation, you basically do the same (on an image not containing any defects). It's ok if the annotation are not perfect, but just rectangles on top of the warp/weft floating points.
> > The number of annotations we use depends on the specific textile, you should find the details in the paper
> 
> Thanks for your reply, I am still not sure how you generated your input mask, is it done by using thresholding or photoshop or both?

are you get answer of this
